name: Backend Dev CD

on:
  workflow_dispatch:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Gradle
        run: ./gradlew clean bootJar -PSERVER_URL=${{ secrets.SERVER_URL }}

      - name: Docker Build
        run: docker build --build-arg PROFILE=dev -t yun8565/mobby-server-dev:latest .

      - name: Docker Push
        run: docker push yun8565/mobby-server-dev:latest

  deploy:
    runs-on: self-hosted
    needs: docker-build

    steps:
      - name: Docker Pull & Run
        run: |
            docker pull yun8565/mobby-server-dev:latest
            docker stop server || true
            docker container prune -f
            docker run -d --name server -p 8080:8080 --network redis-network \
            --env-file ./.env \
            yun8565/mobby-server-dev:latest
